interface Item {
  id: number;
  title: string;
  prizeName: string;  // Changed from prizeName: number to prizeName: string
  startDate: string;  // Changed from number to string for consistency
  endDate: string;
  status: 'Active' | 'Inactive';
  prizeImg: string;
  titleImg: string;
}

export const RaffleCreationData: Item[] = [
  {
    id: 1,
    title: 'iPhone 14 Pro',
    prizeName: 'iPhone 14 Pro',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 2,
    title: 'HP Laptop',
    prizeName: 'HP Laptop',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 3,
    title: 'iPod',
    prizeName: 'iPod',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 4,
    title: 'Yamaha Bike',
    prizeName: 'Yamaha Bike',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 5,
    title: '3 Day Tour',
    prizeName: '3 Day Tour',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 6,
    title: 'MacBook Pro',
    prizeName: 'MacBook Pro',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 7,
    title: 'Samsung Galaxy S21',
    prizeName: 'Samsung Galaxy S21',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 8,
    title: 'Nintendo Switch',
    prizeName: 'Nintendo Switch',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 9,
    title: 'Sony Headphones',
    prizeName: 'Sony Headphones',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 10,
    title: 'AirPods Pro',
    prizeName: 'AirPods Pro',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 11,
    title: 'iPad Air',
    prizeName: 'iPad Air',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 12,
    title: 'Apple Watch Series 6',
    prizeName: 'Apple Watch Series 6',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 13,
    title: 'GoPro Hero 9',
    prizeName: 'GoPro Hero 9',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 14,
    title: 'Fitbit Charge 4',
    prizeName: 'Fitbit Charge 4',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 15,
    title: 'Bose SoundLink',
    prizeName: 'Bose SoundLink',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 16,
    title: 'Dell XPS 13',
    prizeName: 'Dell XPS 13',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 17,
    title: 'Oculus Quest 2',
    prizeName: 'Oculus Quest 2',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 18,
    title: 'Logitech MX Master 3',
    prizeName: 'Logitech MX Master 3',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 19,
    title: 'Microsoft Surface Pro 7',
    prizeName: 'Microsoft Surface Pro 7',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Inactive',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
  {
    id: 20,
    title: 'Razer Blade 15',
    prizeName: 'Razer Blade 15',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'Active',
    prizeImg: '/images/laptop.webp',
    titleImg: '/images/laptop.webp',
  },
];
