interface UserTableType {
id: number;
  name: string;
  email: string;
  address: string;
  registrationDate: string;
  status: 'Active' | 'Inactive';
  kycRequest: 'Approved' | 'Pending';
  imgUrl: string;
}
export const UserData: UserTableType[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'johndoe@example.com',
    address: '123 Main St, New York, NY',
    registrationDate: '2023-01-10',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    address: '456 Oak Ave, Los Angeles, CA',
    registrationDate: '2023-02-15',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 3,
    name: 'Michael Brown',
    email: 'michaelbrown@example.com',
    address: '789 Pine Rd, Chicago, IL',
    registrationDate: '2023-03-20',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 4,
    name: 'Emily Davis',
    email: 'emilydavis@example.com',
    address: '321 Cedar Ln, Houston, TX',
    registrationDate: '2023-04-05',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 5,
    name: 'James Wilson',
    email: 'jameswilson@example.com',
    address: '654 Birch Blvd, Miami, FL',
    registrationDate: '2023-05-12',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 6,
    name: 'Olivia Martinez',
    email: 'oliviamartinez@example.com',
    address: '987 Spruce Ct, Boston, MA',
    registrationDate: '2023-06-18',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 7,
    name: 'William Lee',
    email: 'williamlee@example.com',
    address: '741 Elm St, Denver, CO',
    registrationDate: '2023-07-25',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 8,
    name: 'Sophia Garcia',
    email: 'sophiagarcia@example.com',
    address: '852 Maple Ave, Seattle, WA',
    registrationDate: '2023-08-14',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 9,
    name: 'Benjamin Lopez',
    email: 'benjaminlopez@example.com',
    address: '963 Walnut Way, Austin, TX',
    registrationDate: '2023-09-10',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 10,
    name: 'Charlotte Clark',
    email: 'charlotteclark@example.com',
    address: '159 Chestnut Rd, San Diego, CA',
    registrationDate: '2023-10-01',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 11,
    name: 'Liam Hernandez',
    email: 'liamhernandez@example.com',
    address: '753 Willow Dr, Portland, OR',
    registrationDate: '2023-10-15',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 12,
    name: 'Amelia Moore',
    email: 'ameliamoore@example.com',
    address: '852 Fir Ln, Las Vegas, NV',
    registrationDate: '2023-11-08',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 13,
    name: 'Noah Taylor',
    email: 'noahtaylor@example.com',
    address: '741 Aspen Rd, Dallas, TX',
    registrationDate: '2023-11-21',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 14,
    name: 'Mia Anderson',
    email: 'miaanderson@example.com',
    address: '963 Poplar Blvd, Phoenix, AZ',
    registrationDate: '2023-12-10',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 15,
    name: 'Ethan White',
    email: 'ethanwhite@example.com',
    address: '159 Sycamore St, Orlando, FL',
    registrationDate: '2024-01-05',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 16,
    name: 'Harper King',
    email: 'harperking@example.com',
    address: '753 Redwood Dr, San Francisco, CA',
    registrationDate: '2024-01-25',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 17,
    name: 'Alexander Wright',
    email: 'alexanderwright@example.com',
    address: '852 Hickory Ln, Charlotte, NC',
    registrationDate: '2024-02-14',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 18,
    name: 'Avery Green',
    email: 'averygreen@example.com',
    address: '963 Olive Way, Minneapolis, MN',
    registrationDate: '2024-02-28',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 19,
    name: 'Elijah Baker',
    email: 'elijahbaker@example.com',
    address: '159 Palm Rd, Atlanta, GA',
    registrationDate: '2024-03-10',
    status: 'Active',
    kycRequest: 'Approved',
    imgUrl: '/images/laptop.webp',
  },
  {
    id: 20,
    name: 'Abigail Scott',
    email: 'abigailscott@example.com',
    address: '753 Beech St, Nashville, TN',
    registrationDate: '2024-03-25',
    status: 'Inactive',
    kycRequest: 'Pending',
    imgUrl: '/images/laptop.webp',
  },
];
